#!/bin/sh

echo "Run Formatter..."
dart format --set-exit-if-changed .

echo "Run Analyzer..."
flutter analyze || { echo "flutter analyze error"; exit 1; }

echo "Run Test..."
flutter test || { echo "flutter test fail"; exit 1; }
